twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes:
    - '@TalesFromADevFlowbite/form/default.html.twig'
  file_name_pattern: '*.twig'
  globals:
    env: '%env(resolve:APP_LOGIN_FORM)%'


when@test:
  twig:
    strict_variables: true
